name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install node modules
        run: npm install

      - name: Create build
        run: npm run build
